# Generated by Django 6.0.2 on 2026-02-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='teams.teamdetails')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='teams.teamdetails')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentdetails')),
            ],
            options={
                'verbose_name_plural': 'Create Matches for a Tournament',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('WIN_BY_RUNS', 'Win by Runs'), ('WIN_BY_WICKETS', 'Win by Wickets'), ('TIE', 'Tie'), ('NO_RESULT', 'No Result')], max_length=20)),
                ('win_margin', models.PositiveIntegerField(blank=True, null=True)),
                ('result_summary', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.creatematch')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='teams.teamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL')], max_length=10)),
                ('is_match_started', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_matches', to='teams.teamdetails')),
                ('bowling_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling_matches', to='teams.teamdetails')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_start', to='matches.creatematch')),
                ('toss_loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_toss_matches', to='teams.teamdetails')),
                ('toss_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_toss_matches', to='teams.teamdetails')),
            ],
            options={
                'verbose_name_plural': 'Match Start',
            },
        ),
    ]
