# Generated by Django 6.0.2 on 2026-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_manofthematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manofthematch',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
