# Generated by Django 6.0 on 2026-02-27 09:23

import django.db.models.deletion
from django.db import migrations, models


def forwards_create_tournament_structures(apps, schema_editor):
    TeamDetails = apps.get_model("teams", "TeamDetails")
    PlayerDetails = apps.get_model("teams", "PlayerDetails")
    TournamentTeam = apps.get_model("teams", "TournamentTeam")
    TournamentRoster = apps.get_model("teams", "TournamentRoster")

    # 1) Register all existing teams into their tournaments
    for team in TeamDetails.objects.all().only("id", "tournament_id"):
        if team.tournament_id is None:
            continue
        TournamentTeam.objects.get_or_create(
            tournament_id=team.tournament_id,
            team_id=team.id,
        )

    # 2) Create roster entries from existing PlayerDetails.team assignments
    #    (Old schema: player -> team -> tournament)
    for p in PlayerDetails.objects.all().only(
        "id",
        "team_id",
        "role",
        "is_captain",
        "is_vice_captain",
        "jersey_number",
    ):
        if p.team_id is None:
            continue

        team = TeamDetails.objects.filter(id=p.team_id).only("tournament_id").first()
        if not team or team.tournament_id is None:
            continue

        tt = TournamentTeam.objects.filter(
            tournament_id=team.tournament_id,
            team_id=p.team_id,
        ).first()
        if not tt:
            tt = TournamentTeam.objects.create(
                tournament_id=team.tournament_id,
                team_id=p.team_id,
            )

        TournamentRoster.objects.get_or_create(
            tournament_team_id=tt.id,
            tournament_id=team.tournament_id,
            player_id=p.id,
            defaults={
                "role": p.role,
                "is_captain": p.is_captain,
                "is_vice_captain": p.is_vice_captain,
                "jersey_number": p.jersey_number,
            },
        )

    # 3) Deduplicate teams by name (so CSK is a single global team)
    #    Keep the smallest id per normalized name.
    def norm(name: str) -> str:
        return (name or "").strip().lower()

    canonical_by_norm = {}
    duplicates = []  # (dup_id, canonical_id)

    for t in TeamDetails.objects.all().only("id", "team_name").order_by("id"):
        key = norm(t.team_name)
        if not key:
            continue
        if key not in canonical_by_norm:
            canonical_by_norm[key] = t.id
        else:
            duplicates.append((t.id, canonical_by_norm[key]))

    if not duplicates:
        return

    # Update all FK references from duplicate team ids to canonical team ids.
    CreateMatch = apps.get_model("matches", "CreateMatch")
    MatchStart = apps.get_model("matches", "MatchStart")
    MatchResult = apps.get_model("matches", "MatchResult")
    Innings = apps.get_model("scoring", "Innings")
    KnockoutMatch = apps.get_model("knockout", "KnockoutMatch")

    for dup_id, canon_id in duplicates:
        # matches
        CreateMatch.objects.filter(team1_id=dup_id).update(team1_id=canon_id)
        CreateMatch.objects.filter(team2_id=dup_id).update(team2_id=canon_id)
        MatchStart.objects.filter(toss_winner_id=dup_id).update(toss_winner_id=canon_id)
        MatchStart.objects.filter(toss_loser_id=dup_id).update(toss_loser_id=canon_id)
        MatchStart.objects.filter(batting_team_id=dup_id).update(batting_team_id=canon_id)
        MatchStart.objects.filter(bowling_team_id=dup_id).update(bowling_team_id=canon_id)
        MatchResult.objects.filter(winner_id=dup_id).update(winner_id=canon_id)

        # scoring
        Innings.objects.filter(batting_team_id=dup_id).update(batting_team_id=canon_id)
        Innings.objects.filter(bowling_team_id=dup_id).update(bowling_team_id=canon_id)

        # knockout
        KnockoutMatch.objects.filter(team1_id=dup_id).update(team1_id=canon_id)
        KnockoutMatch.objects.filter(team2_id=dup_id).update(team2_id=canon_id)
        KnockoutMatch.objects.filter(winner_id=dup_id).update(winner_id=canon_id)

        # teams app tables
        TournamentTeam.objects.filter(team_id=dup_id).update(team_id=canon_id)
        PlayerDetails.objects.filter(team_id=dup_id).update(team_id=canon_id)

    # 4) Deduplicate TournamentTeam rows that may collide after team merge
    #    Keep smallest id per (tournament, team)
    seen = {}
    tt_dups = []  # (dup_tt_id, keep_tt_id)
    for tt in TournamentTeam.objects.all().only("id", "tournament_id", "team_id").order_by("id"):
        key = (tt.tournament_id, tt.team_id)
        if key not in seen:
            seen[key] = tt.id
        else:
            tt_dups.append((tt.id, seen[key]))

    for dup_tt_id, keep_tt_id in tt_dups:
        TournamentRoster.objects.filter(tournament_team_id=dup_tt_id).update(tournament_team_id=keep_tt_id)
        TournamentTeam.objects.filter(id=dup_tt_id).delete()

    # 5) Finally delete duplicate TeamDetails rows
    dup_ids = [d for d, _ in duplicates]
    TeamDetails.objects.filter(id__in=dup_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_playerdetails_photo'),
        ('tournaments', '0001_initial'),
        ('matches', '0001_initial'),
        ('scoring', '0001_initial'),
        ('knockout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='teams.teamdetails')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='tournaments.tournamentdetails')),
            ],
            options={
                'verbose_name_plural': 'Tournament Teams',
            },
        ),
        migrations.CreateModel(
            name='TournamentRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALLROUNDER', 'All-Rounder'), ('WICKETKEEPER', 'Wicket Keeper')], default='BATSMAN', max_length=20)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rosters', to='teams.playerdetails')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='tournaments.tournamentdetails')),
                ('tournament_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='teams.tournamentteam')),
            ],
            options={
                'verbose_name_plural': 'Tournament Roster',
            },
        ),
        migrations.RunPython(forwards_create_tournament_structures, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tournamentteam',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='uniq_tournament_team'),
        ),
        migrations.AddConstraint(
            model_name='tournamentroster',
            constraint=models.UniqueConstraint(fields=('tournament', 'player'), name='uniq_player_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentroster',
            constraint=models.UniqueConstraint(fields=('tournament_team', 'player'), name='uniq_player_per_tournament_team'),
        ),
        migrations.RemoveField(
            model_name='playerdetails',
            name='is_captain',
        ),
        migrations.RemoveField(
            model_name='playerdetails',
            name='is_vice_captain',
        ),
        migrations.RemoveField(
            model_name='playerdetails',
            name='jersey_number',
        ),
        migrations.RemoveField(
            model_name='playerdetails',
            name='role',
        ),
        migrations.RemoveField(
            model_name='playerdetails',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamdetails',
            name='tournament',
        ),
    ]
