# Generated by Django 6.0 on 2026-02-27 09:53

from django.db import migrations, models


def backfill_team_codes(apps, schema_editor):
    TeamDetails = apps.get_model("teams", "TeamDetails")
    for t in TeamDetails.objects.all().only("id", "team_code").order_by("id"):
        if not t.team_code:
            t.team_code = f"TM{t.id:06d}"
            t.save(update_fields=["team_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_playerdetails_is_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdetails',
            name='team_code',
            # Step 1: add nullable + NOT unique to avoid SQLite constraint issues
            field=models.CharField(blank=True, null=True, db_index=True, help_text='Unique team ID (auto-generated). Use this to register team in new tournaments.', max_length=12),
        ),
        migrations.RunPython(backfill_team_codes, migrations.RunPython.noop),
        # Step 2: enforce uniqueness after backfill
        migrations.AlterField(
            model_name='teamdetails',
            name='team_code',
            field=models.CharField(blank=True, null=True, db_index=True, help_text='Unique team ID (auto-generated). Use this to register team in new tournaments.', max_length=12, unique=True),
        ),
    ]
