# Generated by Django 6.0.2 on 2026-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentaward',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
