# Generated by Django 6.0.2 on 2026-03-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentdetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uppercategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uppercategory',
            name='updated_at',
        ),
    ]
