# Generated by Django 6.0.2 on 2026-02-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
