# Generated by Django 6.0.2 on 2026-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0002_teamdetails_tournamentdetails_playerdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uppercategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='uppercategory',
            old_name='category_names',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='uppercategory',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='is_vice_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerdetails',
            name='role',
            field=models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALLROUNDER', 'All-Rounder'), ('WICKETKEEPER', 'Wicket Keeper')], default='BATSMAN', max_length=20),
        ),
        migrations.AddField(
            model_name='teamdetails',
            name='team_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdetails',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdetails',
            name='number_of_overs',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='tournamentdetails',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdetails',
            name='tournament_type',
            field=models.CharField(choices=[('BOX_TURF', 'Box Turf'), ('OPEN_GROUND', 'Open Ground'), ('BOX_GROUND', 'Box Ground')], default='BOX_TURF', max_length=20),
        ),
    ]
