# Generated by Django 6.0.2 on 2026-02-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0003_alter_uppercategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='firstcricketapp.teamdetails')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='firstcricketapp.teamdetails')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='firstcricketapp.tournamentdetails')),
            ],
            options={
                'verbose_name_plural': 'Create Matches for a Tournament',
            },
        ),
    ]
