# Generated by Django 6.0.2 on 2026-02-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0004_creatematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL')], max_length=10)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toss', to='firstcricketapp.creatematch')),
                ('toss_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.teamdetails')),
            ],
        ),
    ]
