# Generated by Django 6.0.2 on 2026-02-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0005_toss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toss',
            options={'verbose_name_plural': 'Toss'},
        ),
    ]
