# Generated by Django 6.0.2 on 2026-02-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0007_starttournament_delete_toss'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('BAT', 'BAT'), ('BOWL', 'BOWL')], max_length=10)),
                ('is_match_started', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_start', to='firstcricketapp.creatematch')),
                ('toss_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.teamdetails')),
            ],
            options={
                'verbose_name_plural': 'Match Start',
            },
        ),
    ]
