# Generated by Django 6.0.2 on 2026-02-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0008_matchstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingXI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_xi', to='firstcricketapp.creatematch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.playerdetails')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.teamdetails')),
            ],
            options={
                'verbose_name_plural': 'Playing XI',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
