# Generated by Django 6.0.2 on 2026-02-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0009_playingxi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayingXI',
        ),
    ]
