# Generated by Django 6.0.2 on 2026-02-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0010_delete_playingxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('total_overs', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting', to='firstcricketapp.teamdetails')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling', to='firstcricketapp.teamdetails')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.creatematch')),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('extra_type', models.CharField(choices=[('none', 'None'), ('wide', 'Wide'), ('no_ball', 'No Ball'), ('bye', 'Bye'), ('leg_bye', 'Leg Bye')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='firstcricketapp.playerdetails')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='striker', to='firstcricketapp.playerdetails')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.innings')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.creatematch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.playerdetails')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstcricketapp.teamdetails')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
