# Generated by Django 6.0.2 on 2026-02-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0011_innings_ball_playermatchstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ball',
        ),
    ]
