# Generated by Django 6.0.2 on 2026-02-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0012_delete_ball'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playermatchstatus',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playermatchstatus',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playermatchstatus',
            name='team',
        ),
        migrations.DeleteModel(
            name='Innings',
        ),
        migrations.DeleteModel(
            name='PlayerMatchStatus',
        ),
    ]
