# Generated by Django 6.0.2 on 2026-02-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0013_alter_playermatchstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstart',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_matches', to='firstcricketapp.teamdetails'),
        ),
        migrations.AddField(
            model_name='matchstart',
            name='bowling_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling_matches', to='firstcricketapp.teamdetails'),
        ),
        migrations.AddField(
            model_name='matchstart',
            name='toss_loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_toss_matches', to='firstcricketapp.teamdetails'),
        ),
        migrations.AlterField(
            model_name='matchstart',
            name='toss_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_toss_matches', to='firstcricketapp.teamdetails'),
        ),
    ]
