# Generated by Django 6.0.2 on 2026-02-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0014_matchstart_batting_team_matchstart_bowling_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveIntegerField(choices=[(1, '1st Innings'), (2, '2nd Innings')])),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('total_balls', models.PositiveIntegerField(default=0)),
                ('extras', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('target', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='firstcricketapp.teamdetails')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='firstcricketapp.teamdetails')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='firstcricketapp.creatematch')),
            ],
            options={
                'verbose_name_plural': 'Innings',
                'unique_together': {('match', 'innings_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('WIN_BY_RUNS', 'Win by Runs'), ('WIN_BY_WICKETS', 'Win by Wickets'), ('TIE', 'Tie'), ('NO_RESULT', 'No Result')], max_length=20)),
                ('win_margin', models.PositiveIntegerField(blank=True, null=True)),
                ('result_summary', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='firstcricketapp.creatematch')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='firstcricketapp.teamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('runs_in_over', models.PositiveIntegerField(default=0)),
                ('wickets_in_over', models.PositiveIntegerField(default=0)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowled_overs', to='firstcricketapp.playerdetails')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overs', to='firstcricketapp.innings')),
            ],
            options={
                'unique_together': {('innings', 'over_number')},
            },
        ),
        migrations.CreateModel(
            name='BowlingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('runs_given', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('wides', models.PositiveIntegerField(default=0)),
                ('no_balls', models.PositiveIntegerField(default=0)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scores', to='firstcricketapp.playerdetails')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scorecard', to='firstcricketapp.innings')),
            ],
            options={
                'unique_together': {('innings', 'bowler')},
            },
        ),
        migrations.CreateModel(
            name='BattingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_OUT', 'Not Out'), ('OUT', 'Out'), ('DNB', 'Did Not Bat')], default='NOT_OUT', max_length=10)),
                ('dismissal_info', models.CharField(blank=True, max_length=200, null=True)),
                ('batting_position', models.PositiveIntegerField()),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_scores', to='firstcricketapp.playerdetails')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_scorecard', to='firstcricketapp.innings')),
            ],
            options={
                'ordering': ['batting_position'],
                'unique_together': {('innings', 'batsman')},
            },
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.PositiveIntegerField()),
                ('runs_off_bat', models.PositiveIntegerField(default=0)),
                ('extra_runs', models.PositiveIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('ball_type', models.CharField(choices=[('NORMAL', 'Normal'), ('WIDE', 'Wide'), ('NO_BALL', 'No Ball'), ('BYE', 'Bye'), ('LEG_BYE', 'Leg Bye')], default='NORMAL', max_length=10)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(choices=[('NONE', 'None'), ('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('CAUGHT_AND_BOWLED', 'Caught and Bowled')], default='NONE', max_length=20)),
                ('is_legal_ball', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faced_balls', to='firstcricketapp.playerdetails')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowled_balls', to='firstcricketapp.playerdetails')),
                ('fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fielding_dismissals', to='firstcricketapp.playerdetails')),
                ('player_dismissed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='firstcricketapp.playerdetails')),
                ('over', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='firstcricketapp.over')),
            ],
            options={
                'ordering': ['over__over_number', 'ball_number'],
                'unique_together': {('over', 'ball_number')},
            },
        ),
    ]
