# Generated by Django 6.0.2 on 2026-02-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0015_innings_matchresult_over_bowlingscorecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Player's mobile number used for login (e.g. 9876543210)", max_length=15, null=True, unique=True),
        ),
    ]
