# Generated by Django 6.0.2 on 2026-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0017_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdetails',
            name='number_of_teams',
            field=models.PositiveIntegerField(default=2, help_text='How many teams will participate in this tournament'),
        ),
    ]
