# Generated by Django 6.0.2 on 2026-02-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstcricketapp', '0018_tournamentdetails_number_of_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PQF', 'Pre Quarter Final'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Final')], max_length=10)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_stages', to='firstcricketapp.tournamentdetails')),
            ],
            options={
                'verbose_name_plural': 'Knockout Stages',
                'ordering': ['stage_order'],
                'unique_together': {('tournament', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('team1_label', models.CharField(blank=True, max_length=50)),
                ('team2_label', models.CharField(blank=True, max_length=50)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_match', to='firstcricketapp.creatematch')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fed_by', to='firstcricketapp.knockoutmatch')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_team1_matches', to='firstcricketapp.teamdetails')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_team2_matches', to='firstcricketapp.teamdetails')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_wins', to='firstcricketapp.teamdetails')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='firstcricketapp.knockoutstage')),
            ],
            options={
                'verbose_name_plural': 'Knockout Matches',
                'ordering': ['match_number'],
                'unique_together': {('stage', 'match_number')},
            },
        ),
    ]
