# Generated by Django 6.0.2 on 2026-02-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstcricketapp', '0013_alter_playermatchstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('total_overs', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_batting', to='firstcricketapp.teamdetails')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_bowler', to='firstcricketapp.playerdetails')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_bowling', to='firstcricketapp.teamdetails')),
                ('match_start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='firstcricketapp.matchstart')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_non_striker', to='firstcricketapp.playerdetails')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_striker', to='firstcricketapp.playerdetails')),
            ],
            options={
                'verbose_name_plural': 'Innings',
            },
        ),
    ]
